### ISSUE TITLE
Error : Org could not be found

### ISSUE THREAD

**Issue by omikcity** [webrtc-uwp/ChatterBox#1]
While debuging I am getting Org could not be found error. assembly reference is missing.

**Comment by volkanalkilic** [comment]
Same problem

**Comment by devtronslab** [comment]
+1

**Comment by wictorwilen** [comment]
To fix this; Remove the invalid reference and then add the WebRTC nuget package.

**Comment by tellemstevedave** [comment]
How are you removing the reference?

**Comment by marcblank** [comment]
Ping!  Seeing the same error using VC 2015.  Any help?

**Comment by SergioOpenPeer** [comment]
You should clone https://github.com/webrtc-uwp/ChatterBox-Sample.git where is ChatterBox standalone project that is using nugget WebRtc nugget package, or clone https://github.com/webrtc-uwp/webrtc-uwp-sdk.git (this will clone this repo too) where ChatterBox is part of the solution and it references proper project.

**Comment by marcblank** [comment]
I will try that now; many thanks for the quick response (first time trying to use the package!)

Best,

Marc

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by marcblank** [comment]
Would you mind explaining (briefly; I don’t want to trouble you) why I might want one rather than the other?

Thanks again.

Marc

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by SergioOpenPeer** [comment]
If you just want to know how ChatterBox is working and how webrtc is used to create an application, ChatterBox-Sample is good enough. If you interested in making changes in webrtc itself, then you have to clone other repo.

**Comment by marcblank** [comment]
Great, thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by marcblank** [comment]
One more question, if I could.    All of the projects build properly (thanks).   For the “second” PC running the sample, what files are required (presumably from the Output folder of the solution); I don’t want to build it again on another machine…

Thanks!

Marc

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
